// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SilviaIlieva.Data;

namespace SilviaIlieva.Data.Migrations
{
    [DbContext(typeof(SilviaIlievaDbContext))]
    [Migration("20200227201209_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "9B5FA88B-48C2-435B-B140-5212E669A34B",
                            RoleId = "0909A2A6-81A1-4074-B7F8-C0DC4E7392AB"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SilviaIlieva.Data.Models.Graphic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Graphics");
                });

            modelBuilder.Entity("SilviaIlieva.Data.Models.Illustration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Illustrations");
                });

            modelBuilder.Entity("SilviaIlieva.Data.Models.Motion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Motions");
                });

            modelBuilder.Entity("SilviaIlieva.Data.Models.Painting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Paintings");
                });

            modelBuilder.Entity("SilviaIlieva.Data.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "0909A2A6-81A1-4074-B7F8-C0DC4E7392AB",
                            ConcurrencyStamp = "362343cd-f302-4e62-a4aa-71b4e64cdabf",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("SilviaIlieva.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "9B5FA88B-48C2-435B-B140-5212E669A34B",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1148e1d5-df5c-4bef-8a0e-0643ea91cae6",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "MILEN",
                            PasswordHash = "AQAAAAEAACcQAAAAEEwgQ4Mc/BWkkDMS/fWNat9JLvdu9IyjX1P3yXE7ZIwoX1fJHSaIaQrl0s6bW6IGoQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Milen"
                        });
                });

            modelBuilder.Entity("SilviaIlieva.Data.Models.UtilityData", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UtilityData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "About",
                            Value = @"
<h1>About me</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla pharetra tellus eu dolor convallis faucibus. Quisque hendrerit, orci a sodales convallis, neque justo venenatis diam, vitae semper mauris metus vitae nulla. Etiam at est convallis, ultrices odio in, sagittis libero. Praesent id lorem molestie, commodo ex sit amet, feugiat neque. Sed interdum metus a arcu dapibus suscipit. Vestibulum cursus vitae eros et dapibus. Fusce volutpat commodo ante tempus placerat. Nulla congue leo ac lectus vestibulum, at cursus elit vulputate. Sed pharetra faucibus ante. Donec fringilla orci ut hendrerit vulputate. Phasellus vel lectus ac turpis scelerisque vehicula eget dapibus dolor.</p>
<p>Nulla sit amet mi suscipit, finibus sapien eu, porttitor nulla. Mauris pretium fermentum lorem, ut tincidunt mi sodales vestibulum. Quisque et dapibus dui, eu feugiat enim. Nullam laoreet laoreet tellus, in tempus massa vestibulum eget. Donec pretium elit eu justo egestas congue. Morbi eget quam congue, hendrerit mauris sit amet, accumsan tortor. Phasellus urna lorem, elementum a massa id, dictum facilisis nisl. Nullam tempor laoreet tincidunt. Vivamus et bibendum enim, a sagittis urna. Aenean elementum vel risus a sodales. Integer fringilla interdum orci, at fringilla justo rutrum vitae. Nulla facilisis pretium lacus, quis efficitur diam venenatis at. Nulla ultrices ullamcorper sem, ac accumsan arcu.</p>
<p>Morbi dictum et arcu a congue. In a nibh quis justo aliquet luctus. Praesent volutpat neque malesuada leo efficitur, eu tristique velit varius. In non nibh eleifend, porttitor enim sed, bibendum tortor. Quisque posuere sapien vel efficitur interdum. Maecenas cursus, mi eget aliquet egestas, est felis vestibulum nisi, ac gravida lectus augue eget purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque ornare diam turpis, in molestie justo tempus in. Integer porta condimentum varius. Aliquam rutrum mauris non augue accumsan vulputate. In feugiat lorem massa, non sollicitudin massa porta sed. Donec sapien lectus, scelerisque auctor tempus nec, fermentum ac velit. Fusce ac rutrum neque, quis commodo lacus. Vestibulum condimentum scelerisque tellus ac mattis. Aenean tellus nunc, feugiat ut leo maximus, viverra tincidunt ligula.</p>
<p>Integer id condimentum dui, a porttitor ex. Ut commodo tortor eget nulla imperdiet dignissim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam faucibus arcu sit amet vehicula sodales. Nullam at congue nibh, ac aliquet elit. Praesent ut turpis interdum, dictum lorem in, luctus nibh. Etiam dignissim tincidunt sem, quis dictum ipsum aliquam ac. Integer consequat non tortor eget condimentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed commodo porttitor lacus a elementum. Praesent imperdiet sodales convallis. Vestibulum consectetur nulla lectus, ut ultrices ipsum pellentesque quis.</p>"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Disclaimer",
                            Value = @"
<h1>Disclaimer</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla pharetra tellus eu dolor convallis faucibus. Quisque hendrerit, orci a sodales convallis, neque justo venenatis diam, vitae semper mauris metus vitae nulla. Etiam at est convallis, ultrices odio in, sagittis libero. Praesent id lorem molestie, commodo ex sit amet, feugiat neque. Sed interdum metus a arcu dapibus suscipit. Vestibulum cursus vitae eros et dapibus. Fusce volutpat commodo ante tempus placerat. Nulla congue leo ac lectus vestibulum, at cursus elit vulputate. Sed pharetra faucibus ante. Donec fringilla orci ut hendrerit vulputate. Phasellus vel lectus ac turpis scelerisque vehicula eget dapibus dolor.</p>
<p>Nulla sit amet mi suscipit, finibus sapien eu, porttitor nulla. Mauris pretium fermentum lorem, ut tincidunt mi sodales vestibulum. Quisque et dapibus dui, eu feugiat enim. Nullam laoreet laoreet tellus, in tempus massa vestibulum eget. Donec pretium elit eu justo egestas congue. Morbi eget quam congue, hendrerit mauris sit amet, accumsan tortor. Phasellus urna lorem, elementum a massa id, dictum facilisis nisl. Nullam tempor laoreet tincidunt. Vivamus et bibendum enim, a sagittis urna. Aenean elementum vel risus a sodales. Integer fringilla interdum orci, at fringilla justo rutrum vitae. Nulla facilisis pretium lacus, quis efficitur diam venenatis at. Nulla ultrices ullamcorper sem, ac accumsan arcu.</p>
<p>Morbi dictum et arcu a congue. In a nibh quis justo aliquet luctus. Praesent volutpat neque malesuada leo efficitur, eu tristique velit varius. In non nibh eleifend, porttitor enim sed, bibendum tortor. Quisque posuere sapien vel efficitur interdum. Maecenas cursus, mi eget aliquet egestas, est felis vestibulum nisi, ac gravida lectus augue eget purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque ornare diam turpis, in molestie justo tempus in. Integer porta condimentum varius. Aliquam rutrum mauris non augue accumsan vulputate. In feugiat lorem massa, non sollicitudin massa porta sed. Donec sapien lectus, scelerisque auctor tempus nec, fermentum ac velit. Fusce ac rutrum neque, quis commodo lacus. Vestibulum condimentum scelerisque tellus ac mattis. Aenean tellus nunc, feugiat ut leo maximus, viverra tincidunt ligula.</p>
<p>Integer id condimentum dui, a porttitor ex. Ut commodo tortor eget nulla imperdiet dignissim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam faucibus arcu sit amet vehicula sodales. Nullam at congue nibh, ac aliquet elit. Praesent ut turpis interdum, dictum lorem in, luctus nibh. Etiam dignissim tincidunt sem, quis dictum ipsum aliquam ac. Integer consequat non tortor eget condimentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed commodo porttitor lacus a elementum. Praesent imperdiet sodales convallis. Vestibulum consectetur nulla lectus, ut ultrices ipsum pellentesque quis.</p>"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Cookies",
                            Value = @"
<h1>Cookies</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla pharetra tellus eu dolor convallis faucibus. Quisque hendrerit, orci a sodales convallis, neque justo venenatis diam, vitae semper mauris metus vitae nulla. Etiam at est convallis, ultrices odio in, sagittis libero. Praesent id lorem molestie, commodo ex sit amet, feugiat neque. Sed interdum metus a arcu dapibus suscipit. Vestibulum cursus vitae eros et dapibus. Fusce volutpat commodo ante tempus placerat. Nulla congue leo ac lectus vestibulum, at cursus elit vulputate. Sed pharetra faucibus ante. Donec fringilla orci ut hendrerit vulputate. Phasellus vel lectus ac turpis scelerisque vehicula eget dapibus dolor.</p>
<p>Nulla sit amet mi suscipit, finibus sapien eu, porttitor nulla. Mauris pretium fermentum lorem, ut tincidunt mi sodales vestibulum. Quisque et dapibus dui, eu feugiat enim. Nullam laoreet laoreet tellus, in tempus massa vestibulum eget. Donec pretium elit eu justo egestas congue. Morbi eget quam congue, hendrerit mauris sit amet, accumsan tortor. Phasellus urna lorem, elementum a massa id, dictum facilisis nisl. Nullam tempor laoreet tincidunt. Vivamus et bibendum enim, a sagittis urna. Aenean elementum vel risus a sodales. Integer fringilla interdum orci, at fringilla justo rutrum vitae. Nulla facilisis pretium lacus, quis efficitur diam venenatis at. Nulla ultrices ullamcorper sem, ac accumsan arcu.</p>
<p>Morbi dictum et arcu a congue. In a nibh quis justo aliquet luctus. Praesent volutpat neque malesuada leo efficitur, eu tristique velit varius. In non nibh eleifend, porttitor enim sed, bibendum tortor. Quisque posuere sapien vel efficitur interdum. Maecenas cursus, mi eget aliquet egestas, est felis vestibulum nisi, ac gravida lectus augue eget purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque ornare diam turpis, in molestie justo tempus in. Integer porta condimentum varius. Aliquam rutrum mauris non augue accumsan vulputate. In feugiat lorem massa, non sollicitudin massa porta sed. Donec sapien lectus, scelerisque auctor tempus nec, fermentum ac velit. Fusce ac rutrum neque, quis commodo lacus. Vestibulum condimentum scelerisque tellus ac mattis. Aenean tellus nunc, feugiat ut leo maximus, viverra tincidunt ligula.</p>
<p>Integer id condimentum dui, a porttitor ex. Ut commodo tortor eget nulla imperdiet dignissim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam faucibus arcu sit amet vehicula sodales. Nullam at congue nibh, ac aliquet elit. Praesent ut turpis interdum, dictum lorem in, luctus nibh. Etiam dignissim tincidunt sem, quis dictum ipsum aliquam ac. Integer consequat non tortor eget condimentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed commodo porttitor lacus a elementum. Praesent imperdiet sodales convallis. Vestibulum consectetur nulla lectus, ut ultrices ipsum pellentesque quis.</p>"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SilviaIlieva.Data.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SilviaIlieva.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SilviaIlieva.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("SilviaIlieva.Data.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SilviaIlieva.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SilviaIlieva.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
